### PR TITLE
Update Tutorials with Data Stories

### PR DESCRIPTION
**Pull request by cassienickles**
Added in Data Story Notebooks from Cloud Playground Development so they live in the cookbook. Updated the tutorials index page and the _quarto.yml

### CODE REVIEW

**Comment by jules32** [comment]
Thanks Cassie! Reviewing now

**Comment by jules32** [comment]
@cassienickles, I'm getting a quarto build error and traced it back to this notebook. Would you be able to run it and see if you know how to troubleshoot? Happy to screenshare and do it together too if you'd prefer.

`Observing_Seasonal_Ag_Changes.ipynb`

**Comment by cassienickles** [comment]
@jules32 it should work now! I fixed some syntax errors, let me know if it works for you.

**Review by jules32 — APPROVED** [review]
Thanks for revisiting those files Cassie, it builds fine now! Great job, and merging :)

**Pull request merged**
