### PR TITLE
Add R code for a single COG access

### PR DESCRIPTION
**Pull request by mjami00**
@jules32, Please take a look at this at your convenience.

### CODE REVIEW

**Comment by mjami00** [comment]
I see failing checks for rendering and deploying quarto files

**Comment by jules32** [comment]
Hi @mjami00 ! I added `eval: execute: false` to the yaml up top and it now builds for me without error (locally). Have a look and let me know if you'd like me to approve this pull request! 

I'll be able to review more deeply and tidy during Thursday CoWorking.

**Comment by mjami00** [comment]
Thanks for the updates, please go ahead and approve this. Thanks!

**Review by jules32 — APPROVED** [review]
I approve!

**Comment by mjami00** [comment]
Thanks!

**Pull request merged**
