### PR TITLE
Add link to https://guide.cloudnativegeo.org/

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**

### CODE REVIEW

**Comment by abarciauskas-bgse** [comment]
@wildintellect @jules32

**Comment by jules32** [comment]
Thank you @abarciauskas-bgse ! 

cc: @alexishunzinger, @BriannaLind @cassienickles , would one of you like to review and merge these few lines that Aimee added to link to https://guide.cloudnativegeo.org/? 

I know we'll be revamping the Welcoming sections including this ["Our Cookbook" section](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/our-cookbook.html), but I think this is the best place for now and it would be great to include. Thank you!

**Review by BriannaLind — APPROVED** [review]
This looks great, thanks for adding this @abarciauskas-bgse !

**Comment by BriannaLind** [comment]
@jules32 ..... I think I did it!

**Pull request merged**
