### PR TITLE
Dev contributing

### PR DESCRIPTION
**Pull request by jules32**
Hi - there are 3 commits that you can review in the tabs above this comment; you'll see one is adding/renaming "recipes/how to" chapters to match Catalina's cheatsheet structure, and the second is to add starting Mentors onboarding text.

### CODE REVIEW

**Comment by jules32** [comment]
Tagging @erinmr and @ScienceCat18 if either of you would be able to review (you'll have a yellow banner at the top of this page) and then merge!

**Review by erinmr — APPROVED** [review]
Looks great

**Comment by erinmr** [comment]
@jules32 branch is ready to delete when you are

**Comment by jules32** [comment]
Thank you! Deleting :)

**Pull request merged**
