### PR TITLE
make environment chapter

### PR DESCRIPTION
**Pull request by jules32**
We need to add more content here

### CODE REVIEW

**Comment by erinmr** [comment]
Adding notes here -> https://docs.google.com/document/d/1531MUAxwOT-x0Ij0Sz_OJR0K4fzXeQ3Cy_W9YO-yXrU/edit

**Comment by jules32** [comment]
I will bring @erinmr 's notes into this chapter and publish it in the Cookbook. Then we can continue updating from conversations with @betolink @virdi https://github.com/NASA-Openscapes/corn/issues/20

**Comment by jules32** [comment]
Ready to review and merge @betolink or @virdi

**Comment by jules32** [comment]
Here's the current view: 
image

**Comment by stefaniebutland** [comment]
reviewing and merging with @virdi Tues Jun 27

**Review by stefaniebutland — APPROVED** [review]
reviewed in coworking w @virdi. Ready to merge!

**Pull request merged**
