### PR TITLE
Edit howto structure

### PR DESCRIPTION
**Pull request by andypbarrett**
We've regorg'd the how-to menu structure see #181

We need:

- regorganize file structure
- change filenames

### CODE REVIEW

**Comment by andypbarrett** [comment]
I'm listing tasks here from comments in the `_quarto.yml` files.

- [ ] - Rename `how-tos/working-with-data-in-cloud/index.md` as `how-tos/if-im-in-the-cloud.qmd`
- [ ] - In (above) new file, either include or add links to 
```
              - text: "Direct Cloud Access"
                href: how-tos/working-with-data-in-cloud/Direct-Cloud-Access.qmd
              - text: "Access Data behind a EULA" 
                href: how-tos/working-with-data-in-cloud/Access-EULA-Data.qmd
``` 
- [ ] - Create `if-im-local.qmd`
- [ ] - In `if-im-local.qmd`, either include content or add links to
```
         - section: how-tos/working-locally/index.md
           contents:
             - text: "Download Data"
               href: how-tos/working-locally/download.qmd
```
- [ ] - Rename   `how-tos/subset/index.md` to `subset.qmd`
- [ ] - Create `reformat-data.qmd`
- [ ] - Create `aggregate.qmd`
- [ ] - Create `use-apis.qmd` with short descriptions of Harmony, OPenDAP, etc and when to use them.

**Comment by andypbarrett** [comment]
Each of the above tasks could/should be separate issues/stories.  Some might need to be fleshed out further

**Comment by jules32** [comment]
Awesome Andy; I've blocked time Monday afternoon to contribute to this and am happy to cowork/screenshare with anyone then

**Comment by jules32** [comment]
I've taken care of the whole checklist above. Additionally, 

- [x] change `how-tos/plot/index.md` to `how-tos/plot.qmd`
- [x] change `how-tos/reproject_and_regrid/index.md` to `how-tos/reproject_and_regrid.qmd`

**Pull request merged**
