### PR TITLE
delete authenticate as its own how-to chapter

### PR DESCRIPTION
**Pull request by jules32**
another item on the Cookbook reorganization: delete Authentication chapter and reminder for `earthaccess` 

@betolink @andypbarrett @asteiker

### CODE REVIEW

**Comment by betolink** [comment]
I was thinking that instead of deleting this section maybe we should updated it and move it to an appendix. Authentication with Python is semi trivial with `earthaccess` but people sometimes use lower level APIs and they need to know how the internals work, e.g. cloud vs on-prem.

**Comment by jules32** [comment]
Ah, an Appendix is a good idea so that alternatives can live there but we can still have our opinionated approach.

**Comment by jules32** [comment]
Hi @betolink , picking up this thread - I've moved the authentication.md file to the appendix. It still needs to be updated with the current preferred approach but I wanted to help with the quarto architecture

**Review by mjami00 — APPROVED** [review]

**Comment by mjami00** [comment]
Looking good!

**Pull request merged**
