### PR TITLE
Fixup Is2 harmony notebook

### PR DESCRIPTION
**Pull request by andypbarrett**
The IS2 Harmony notebook that describes how to subset ICESat-2 granules using harmony had been modified.

Make tutorial steps sequentials by removing extra information to appendices
Modify text and remove unnecessary print statements - Jupyter will output results etc without a print statement
Add image to show subset area of interest
Add large order guidance to Appendix

### CODE REVIEW

**Comment by asteiker** [comment]
@andypbarrett I pushed up a few updates and comments in _italics_. Overall this is looking great. I didn't open a review yet - perhaps you could address my initial comments and then I can do one more review to move out of draft PR state? I recommended a few areas that we could pull out into a version 2, including much of the appendix section and "choose my own s3 bucket" use case. 

I also had some issues with xarray but I think this is a "me" problem - I was installing another library and it may have messed with my kernel. Lmk if you can reproduce, otherwise ignore.

**Comment by andypbarrett** [comment]
I'll take a look at this before standup and get it ready for review.

**Comment by jules32** [comment]
Looks really great @asteiker and @andypbarrett ! We discussed/screenshared today with @asteiker and @danielfromearth. Amy has some notes about how to frame this as "subsetting with harmony" tutorial, using ICESAT2 data. And here is an example with TEMPO data: https://nasa.github.io/ASDC_Data_and_User_Services/TEMPO/tempo_with_harmony-py_clean.html

**Review by jules32 — APPROVED** [review]

**Comment by ateucher** [comment]
Hi all, I hope you don't mind my unsolicited appearance here! I came by to see if the deploy preview was working (yay, it is!), and I noticed the addition of `tutorials/make_atl03_figure.ipynb` (https://deploy-preview-365--super-malabi-c81e61.netlify.app/tutorials/make_atl03_figure). Is this a page that should be added to the tutorials section of `_quarto.yml`?

**Review by asteiker — APPROVED** [review]

**Pull request merged**
