### PR TITLE
Add pygeoweaver demo of how to reuse FAIRable workflows

### PR DESCRIPTION
**Pull request by ZihengSun**
## What is in this PR?

Based on the amazing tutorials introduced by Amy, we converted the steps of the tutorials into a FAIRable workflow, and this notebook will show how to download the workflow, browse details of the workflow, and edit the process code, and re-run the workflow and check history.

FAIRable workflow is the key to enhance our productivity as a community, especially for use cases like [Earth AI](https://www.sciencedirect.com/user/identity/landing?code=VJsVmpEYTf0CRnMvqkPtDTyNEa2vtWr2Ya845uG7&state=retryCounter%3D0%26csrfToken%3Deeeae572-850d-4555-a4e7-177dbe2e6175%26idpPolicy%3Durn%253Acom%253Aelsevier%253Aidp%253Apolicy%253Aproduct%253Ainst_assoc%26returnUrl%3D%252Fscience%252Farticle%252Fpii%252FS0098300422000036%26prompt%3Dnone%26cid%3Darp-96d26805-39d3-4087-8d7a-4924c43cbca1) which is full of uncertainties and RRR (reproducibility, replicability, and reusability) challenges. We must adopt tools to help us ensure the bottomline that our work (everyone's time and efforts) is sharable and continuable by other colleges, and no work is wasted on reinventing wheels, or duplicating previous experiments, or solving the issues that have already been solved many times by others. 

## References

As we discussed about the documentation, we did use help from AI to create some good documentation: https://gokulprathin8.github.io/pygeoweaver-docs.github.io/docs/getting-started (this is the temp link and we will move it to a permanent link soon). Any suggestions would be welcome!

### CODE REVIEW

**Comment by jules32** [comment]
This is super Ziheng, thank you for contributing! 🎉  The Mentors will review and get this in the Cookbook!

**Comment by ZihengSun** [comment]
hello @jules32 this should be ready for testing and review, anything please let us know :)

**Comment by stefaniebutland** [comment]
Hi @ZihengSun! Thank you for this pull request. I'll arrange with one of the Mentors to test, review, and merge

**Comment by ZihengSun** [comment]
> Hi @ZihengSun! Thank you for this pull request. I'll arrange with one of the Mentors to test, review, and merge

Thanks @stefaniebutland ! Yeah, let us know if any requested changes :) Have a happy weekend!

**Comment by stefaniebutland** [comment]
To have this included in the Cookbook, please edit `_quarto.yml` file to add
```
          - href: tutorials/fair-workflow-geoweaver-demo.ipynb
            text: "pygeoweaver demo"
```
so that it will show up in Tutorials section as below. We can merge the pull request once that's done.

```
      - section: tutorials/index.qmd
        contents:
          - href: external/How_to_Perform_Cross-DAAC_S3_Bucket_Access_Using_Python.ipynb
            text: "Multi-datasets 1"
          - href: external/IS2_cloud_Landsat_integration.ipynb
            text: "Multi-datasets 2"
          - href: external/Sea_level_rise_notebook.ipynb
            text: "Sea Level Rise: `earthaccess`"
          - href: tutorials/04_On-Prem_Cloud.ipynb
            text: "Cloud & Non-cloud"
          - href: examples/Earthdata-cloud-clinic.ipynb
            text: "Earthdata Cloud Clinic"
          - href: tutorials/earthaccess-demo.ipynb
            text: "`earthaccess` Python library"
          - href: tutorials/fair-workflow-geoweaver-demo.ipynb
            text: "pygeoweaver demo"
```

**Review by stefaniebutland — APPROVED** [review]
looks good to me!

**Comment by stefaniebutland** [comment]
@ZihengSun Please check that it appears as you expect: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/fair-workflow-geoweaver-demo.html

Thank you again and thanks to @battistowx for reviewing. This is helping us figure out how to improve our Contributing documentation too!

**Pull request merged**
