### PR TITLE
Catalina's Clinic notebook; deleted Amy's original

### PR DESCRIPTION
**Pull request by jules32**
@ScienceCat18 this is your notebook, added to the Cookbook in place of Amy's original.

### CODE REVIEW

**Comment by jules32** [comment]
Note that your notebook is large (>40mb), so I kept getting an error when I tried to push: 

```
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
```

@andypbarrett was able to help me troubleshoot, finding this StackOverflow page that showed how to increase the limit: https://stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request

Commands that fixed the problem:

```
config http.postBuffer 10000000
git push -u origin clinic-2024
```

My next commit will tighten the Clinic a bit, but likely won't make it smaller

**Comment by ScienceCat18** [comment]
I saved it with cells executed so that’s likely why. I can send an un-executed one if that helps.
Catalina



From: Julia Stewart Lowndes ***@***.***>
Reply-To: NASA-Openscapes/earthdata-cloud-cookbook ***@***.***>
Date: Tuesday, April 16, 2024 at 11:23 AM
To: NASA-Openscapes/earthdata-cloud-cookbook ***@***.***>
Cc: "Taglialatela, Catalina M (US 398P)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-Openscapes/earthdata-cloud-cookbook] Catalina's Clinic notebook; deleted Amy's original (PR #322)


Note that your notebook is large (>40mb), so I kept getting an error when I tried to push:

error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400

send-pack: unexpected disconnect while reading sideband packet

@andypbarrett<https://urldefense.us/v3/__https:/github.com/andypbarrett__;!!PvBDto6Hs4WbVuu7!MvYOnnXek5Cta-TgIUaMKFucyK-7z-fcZPZam-XjMyyfAXBLz00PDOnF58yxl6eEDp0vP-MknIwUZfXQhx1W7lOxI7fEyJMc$> was able to help me troubleshoot, finding this StackOverflow page that showed how to increase the limit: https://stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request<https://urldefense.us/v3/__https:/stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request__;!!PvBDto6Hs4WbVuu7!MvYOnnXek5Cta-TgIUaMKFucyK-7z-fcZPZam-XjMyyfAXBLz00PDOnF58yxl6eEDp0vP-MknIwUZfXQhx1W7lOxI-RCd_s7$>

Commands that fixed the problem:

config http.postBuffer 10000000

git push -u origin clinic-2024

My next commit will tighten the Clinic a bit, but likely won't make it smaller

**Comment by ScienceCat18** [comment]
Here is an un-executed notebook, 34KB. Side note, on my end the one I sent yesterday is 31.1 MB, so <40MB. But not sure what’s going on.

Catalina





From: Julia Stewart Lowndes ***@***.***>
Reply-To: NASA-Openscapes/earthdata-cloud-cookbook ***@***.***>
Date: Tuesday, April 16, 2024 at 11:23 AM
To: NASA-Openscapes/earthdata-cloud-cookbook ***@***.***>
Cc: "Taglialatela, Catalina M (US 398P)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-Openscapes/earthdata-cloud-cookbook] Catalina's Clinic notebook; deleted Amy's original (PR #322)


Note that your notebook is large (>40mb), so I kept getting an error when I tried to push:

error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400

send-pack: unexpected disconnect while reading sideband packet

@andypbarrett<https://urldefense.us/v3/__https:/github.com/andypbarrett__;!!PvBDto6Hs4WbVuu7!MvYOnnXek5Cta-TgIUaMKFucyK-7z-fcZPZam-XjMyyfAXBLz00PDOnF58yxl6eEDp0vP-MknIwUZfXQhx1W7lOxI7fEyJMc$> was able to help me troubleshoot, finding this StackOverflow page that showed how to increase the limit: https://stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request<https://urldefense.us/v3/__https:/stackoverflow.com/questions/62753648/rpc-failed-http-400-curl-22-the-requested-url-returned-error-400-bad-request__;!!PvBDto6Hs4WbVuu7!MvYOnnXek5Cta-TgIUaMKFucyK-7z-fcZPZam-XjMyyfAXBLz00PDOnF58yxl6eEDp0vP-MknIwUZfXQhx1W7lOxI-RCd_s7$>

Commands that fixed the problem:

config http.postBuffer 10000000

git push -u origin clinic-2024

My next commit will tighten the Clinic a bit, but likely won't make it smaller

**Comment by jules32** [comment]
@ScienceCat18 this is all set for you now. I moved the harmony intro to the end as bonus (so you don't have to mention it at the beginning and can get to the code sooner). I cleared all cells after running until you noted it wasn't working. 

Your next steps: 

- In the Hub, go to the GitHub tab and pull; you can then select the clinic-2024 branch. 
- Open the clinic file: it's in tutorials/Earthdata-cloud-clinic.ipynb
- Execute the cells, update the data with any other examples/delete what isn't working. This is already a lot of good stuff!

**Review by ScienceCat18 — APPROVED** [review]
Thanks Julie, looks good.

**Pull request merged**
