### PR TITLE
Cloud clinic

### PR DESCRIPTION
**Pull request by asteiker**
@jules32 I have not yet updated the quarto yml to add the notebook in the TOC. I also did not test quarto's image caption formatting in the notebook.

### CODE REVIEW

**Comment by jules32** [comment]
I've started by reading and lightly editing the [Google Doc](https://docs.google.com/document/d/1KUGi2RSsz1I1xMvQ3i8xSFn0tdeYva6WTnnencReN0I/edit#), and am now following along in the JupyterHub after Kernel > ‘Restart Kernel and Clear All Outputs’. 

I got this warning upon loading libraries, is there a way to suppress so not worrisome for learners?

image

**Comment by andypbarrett** [comment]
Try this at the top of your imports

```
import warnings
warnings.simplefilter("ignore")
```

https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings

**Comment by jules32** [comment]
@asteiker will this (screenshot below) give folks a problem in the Harmony portion of the Clinic if they haven't already set up a .netrc file? Or does `earthaccess` do this in the background for folks and so this will be smooth since they've already run 
`auth = earthaccess.login(strategy="interactive", persist=True)`?

image

**Comment by jules32** [comment]
Hi @asteiker, I've gone through and have been able to run all the code and build the quarto book! I will push that all now. 

All my edits were about clarity for the teaching flow, and with that, the headers. Please please undo/take further any of the changes I made. Here are a few high-level things: 
- I removed numbering except for 1. earthaccess and 2. harmony-py (and focused on this being the distinction in the intro paragraph rather than direct access v subsetting)
- I moved the subsetting graphic earlier since subsetting of some kind is part of both
- headers - I tried to make them more succinct and somewhat comparable between the two methods. Screenshots:

image

image

## Next steps

- Will you please pull this `cloud-clinic` branch and review my updates and make any further changes you'd like
- You can then from the terminal type `quarto render examples/Earthdata-cloud-clinic.ipynb` and this will render this notebook for Quarto. I've already added it to the `_quarto.yml` so then when we merge to the main branch it will show up in the Cookbook
- Let me know if you have any trouble/want to talk about merging and I can help! I can plan to review tomorrow morning before the Clinic too if you need me to

**Comment by jules32** [comment]
OK, pushed! And thanks @andypbarrett for the python warnings help :)

**Comment by asteiker** [comment]
@jules32:

- I still can't get around the Holoviews warning (I also attempted this yesterday and couldn't seem to get it to go away!)
- As far as the Harmony .netrc access, yes earthaccess should be creating a netrc using the persist flag - I tested this.
- The rendering worked great, along with all your helpful updates. Everything looks fantastic - thanks for all your help and for your thoughtful review.

**Comment by asteiker** [comment]
@jules32 Great let's do it together! I still need an approved review in order to merge as well. I made a small update to clarify earthaccess provides data searching and accessing capabilities, with xarray providing the subsetting. 

The warning is still showing up for me in the import code block, so this is first up for me. But I can explain the warning message.

**Pull request merged**
