### PR TITLE
Fix cloud clinic redirect

### LINKED ISSUE #323: Fix Cloud Clinic Redirect
Hi @ateucher !

Would you mind checking and fixing the redirect/alias in Quarto for the Earthdata Cloud Clinic ([source ipynb](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/tutorials/Earthdata-cloud-clinic.ipynb))? 

I used this approach from the [quarto redirects documentation ](https://quarto.org/docs/websites/website-navigation.html#redirects): 

```
---
title: "Earthdata Cloud Clinic"
aliases:
  - examples/Earthdata-cloud-clinic.html
---
```

This was trying to solve: 

This old link: 
https://nasa-openscapes.github.io/earthdata-cloud-cookbook/examples/Earthdata-cloud-clinic.html
Should redirect to new location: 
https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/Earthdata-cloud-clinic.html

### PR DESCRIPTION
**Pull request by ateucher**
Use `/` for site root dir in which to find `/examples/earthdata-cloud-clinic.html` for redirect. I also removed the duplicated title (it was in the yaml metadata and as a H1 header.

This closes #323

### CODE REVIEW

**Comment by ateucher** [comment]
@jules32 This works with a local preview so I think it should be fine, but the only way to test for sure will be to merge and deploy the site

**Review by jules32 — APPROVED** [review]
Thank you so much Andy! This is so great.

**Comment by ateucher** [comment]
Looks like it worked: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/examples/Earthdata-cloud-clinic.html now redirects to https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/Earthdata-cloud-clinic.html

**Comment by jules32** [comment]
Awesome, thank you so much!

**Pull request merged**
