### PR TITLE
Add wget and curl to How Tos

### PR DESCRIPTION
**Pull request by jules32**
Addresses https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/329
Create access-data-command-line.md

**The Plan:** Add a page to the Cookbook that links to this, with additional narration based on what works for us. https://urs.earthdata.nasa.gov/documentation/for_users/data_access/curl_and_wget 

**Goal:** one place for the instructions (urs.earthdata.access.gov), and share with them to help update/clarify this tutorial. And then we focus (opinionated) on python, R, MATLAB, etc maintenance 

Example of what we are shooting for: https://openscapes.github.io/approach-guide/approach/documentation.html#make-our-documentation-citable (It links to somewhere that already has these instructions, but with additional narrations)

### CODE REVIEW

**Comment by jules32** [comment]
Tagging @mjami00 @asteiker @andypbarrett @celiaou-podaac @alexishunzinger @ateucher @cboettig from Coworking

**Comment by jules32** [comment]
Thank you @mjami00, this is so great ! I will change this from "draft pull request" to a "ready for review" pull request and tag @asteiker and @celiaou-podaac as reviewers. Amy/Celia please add any further narration/formatting as you review and let us know if you would like help reviewing or merging :)

**Comment by celiaou-podaac** [comment]
This looks great! I don't have anything to add or change.

**Comment by asteiker** [comment]
@celiaou-podaac @mjami00 Thank you so much for the content and review! Apologies I didn't get a chance to look more closely until now. Did we not add this to the yml on purpose to review further until it's added to the TOC? Does it make sense to open up a new issue for that and keep this branch open?

**Comment by jules32** [comment]
Great spot @asteiker that we needed to add it to the _quarto.yml. I have done so and merged into the Cookbook! Awesome job everyone!

**Comment by mjami00** [comment]
[heart]         Jami, Mahsa (Contractor) reacted to your message:
________________________________
From: Julia Stewart Lowndes ***@***.***>
Sent: Friday, May 31, 2024 7:11:20 PM
To: NASA-Openscapes/earthdata-cloud-cookbook ***@***.***>
Cc: Jami, Mahsa (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-Openscapes/earthdata-cloud-cookbook] Add wget and curl to How Tos (PR #330)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Great spot @asteiker<https://github.com/asteiker> that we needed to add it to the _quarto.yml. I have done so and merged into the Cookbook! Awesome job everyone!

**Pull request merged**
